sudo: required
services:
  - docker

before_install:
  - docker build -t ajayvedwa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajayvedwa/docker-react npm run test -- --coverage
