sudo: required
services:
  - docker

before_install:
  - docker build -t ajayvedwa/docker-react -f Dockerfile .

script:
  - docker run -e CI=true ajayvedwa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-882053630588"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
